// seedData.ts

export interface SeedDeck {
  id: number;
  title: string;
  description?: string;
  imageUrl?: string;
}

export interface SeedCard {
  front_text: string;
  back_text: string;
  deck_id: number;
}

export const seedDecks: SeedDeck[] = [
  {
    id: 1,
    title: 'English Vocabulary',
    description: 'Core high-frequency English words (NGSL)',
    imageUrl: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?q=80&w=2346&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'
  },
  {
    id: 2,
    title: 'Phrasal Verbs',
    description: 'Common separable & inseparable phrasal verbs',
    imageUrl: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?q=80&w=2428&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'
  },
  {
    id: 3,
    title: 'TOEIC Vocabulary',
    description: '600 essential words for the TOEIC test',
    imageUrl: 'https://images.unsplash.com/photo-1606326608606-aa0b62935f2b?q=80&w=2340&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'
  },
  {
    id: 4,
    title: 'Business English',
    description: 'Key terms used in corporate and finance contexts',
    imageUrl: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 5,
    title: 'Office Environment & Procedures',
    description: 'Vocabulary related to office settings and daily tasks.',
    imageUrl: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?q=80&w=2340&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'
  },
  {
    id: 6,
    title: 'Meetings & Presentations',
    description: 'Terms and phrases for meetings and giving presentations.',
    imageUrl: 'https://images.unsplash.com/photo-1560264280-88b68371db39?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 7,
    title: 'Travel & Accommodation',
    description: 'Vocabulary for booking trips, hotels, and transportation.',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 8,
    title: 'Dining Out & Social Events',
    description: 'Words and phrases for restaurants and social gatherings.',
    imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 9,
    title: 'Shopping & Services',
    description: 'Vocabulary related to purchasing goods and using services.',
    imageUrl: 'https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 10,
    title: 'Banking & Finance (Advanced)',
    description: 'More specific terms in banking and financial transactions.',
    imageUrl: 'https://images.unsplash.com/photo-1518458028785-8fbcd101ebb9?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 11,
    title: 'Human Resources & Personnel',
    description: 'Vocabulary for job applications, interviews, and employee relations.',
    imageUrl: 'https://images.unsplash.com/photo-1516321497487-e288fb19713f?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 12,
    title: 'Manufacturing & Production',
    description: 'Terms used in factories, production lines, and logistics.',
    imageUrl: 'https://plus.unsplash.com/premium_photo-1661878008007-7a13bf31c14b?q=80&w=2340&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'
  },
  {
    id: 13,
    title: 'Marketing & Advertising',
    description: 'Vocabulary for marketing campaigns, branding, and sales.',
    imageUrl: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 14,
    title: 'Technology & IT',
    description: 'Terms related to computers, software, and the internet.',
    imageUrl: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 15,
    title: 'Real Estate & Housing',
    description: 'Vocabulary for buying, selling, and renting properties.',
    imageUrl: 'https://images.unsplash.com/photo-1582407947304-fd86f028f716?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 16,
    title: 'Health & Medical',
    description: 'Terms related to health, doctor visits, and medical conditions.',
    imageUrl: 'https://plus.unsplash.com/premium_photo-1673953509975-576678fa6710?q=80&w=2340&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'
  },
  {
    id: 17,
    title: 'Legal Matters (Basic)',
    description: 'Basic legal terms encountered in business contexts.',
    imageUrl: 'https://images.unsplash.com/photo-1589994965851-a8f479c573a9?q=80&w=2340&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'
  },
  {
    id: 18,
    title: 'Weather & Environment',
    description: 'Vocabulary related to weather forecasts and environmental issues.',
    imageUrl: 'https://images.unsplash.com/photo-1561471026-0bbb77535d25?q=80&w=2340&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'
  },
  {
    id: 19,
    title: 'News & Media',
    description: 'Terms used in news reports, articles, and media.',
    imageUrl: 'https://images.unsplash.com/photo-1495020689067-958852a7765e?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 20,
    title: 'Gerunds & Infinitives',
    description: 'Practice distinguishing and using gerunds and infinitives.',
    imageUrl: 'https://plus.unsplash.com/premium_photo-1666739032615-ecbd14dfb543?q=80&w=2340&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'
  }
];

export interface SeedCard {
  front_text: string;
  back_text: string;
  deck_id: number;
}

export const seedCards: SeedCard[] = [
  // English Vocabulary (deck_id: 1) - Total 20
  { front_text: 'time', back_text: 'thời gian', deck_id: 1 },
  { front_text: 'people', back_text: 'người', deck_id: 1 },
  { front_text: 'year', back_text: 'năm', deck_id: 1 },
  { front_text: 'work', back_text: 'công việc', deck_id: 1 },
  { front_text: 'way', back_text: 'cách (thức)', deck_id: 1 },
  { front_text: 'day', back_text: 'ngày', deck_id: 1 },
  { front_text: 'thing', back_text: 'thứ, đồ vật', deck_id: 1 },
  { front_text: 'man', back_text: 'đàn ông', deck_id: 1 },
  { front_text: 'world', back_text: 'thế giới', deck_id: 1 },
  { front_text: 'life', back_text: 'cuộc sống', deck_id: 1 },
  { front_text: 'hand', back_text: 'bàn tay', deck_id: 1 },
  { front_text: 'part', back_text: 'phần', deck_id: 1 },
  { front_text: 'child', back_text: 'trẻ em', deck_id: 1 },
  { front_text: 'eye', back_text: 'mắt', deck_id: 1 },
  { front_text: 'woman', back_text: 'phụ nữ', deck_id: 1 },
  { front_text: 'place', back_text: 'nơi', deck_id: 1 },
  { front_text: 'week', back_text: 'tuần', deck_id: 1 },
  { front_text: 'case', back_text: 'trường hợp', deck_id: 1 },
  { front_text: 'point', back_text: 'điểm', deck_id: 1 },
  { front_text: 'government', back_text: 'chính phủ', deck_id: 1 },

  // Phrasal Verbs (deck_id: 2) - Total 20
  { front_text: 'fill in', back_text: 'điền vào (mẫu đơn)', deck_id: 2 },
  { front_text: 'bring up', back_text: 'nêu lên (vấn đề)', deck_id: 2 },
  { front_text: 'pick up', back_text: 'đón; nhặt lên', deck_id: 2 },
  { front_text: 'turn down', back_text: 'từ chối; vặn nhỏ', deck_id: 2 },
  { front_text: 'break down', back_text: 'hư hỏng; phân tích', deck_id: 2 },
  { front_text: 'look up', back_text: 'tra cứu', deck_id: 2 },
  { front_text: 'take off', back_text: 'cất cánh; cởi ra', deck_id: 2 },
  { front_text: 'put on', back_text: 'mặc vào', deck_id: 2 },
  { front_text: 'get along', back_text: 'hòa hợp', deck_id: 2 },
  { front_text: 'run out of', back_text: 'hết sạch', deck_id: 2 },
  { front_text: 'call off', back_text: 'hủy bỏ', deck_id: 2 },
  { front_text: 'give up', back_text: 'từ bỏ', deck_id: 2 },
  { front_text: 'go on', back_text: 'tiếp tục', deck_id: 2 },
  { front_text: 'set up', back_text: 'thiết lập, thành lập', deck_id: 2 },
  { front_text: 'work out', back_text: 'tập thể dục; tìm ra giải pháp', deck_id: 2 },
  { front_text: 'figure out', back_text: 'hiểu ra, tìm ra', deck_id: 2 },
  { front_text: 'look after', back_text: 'chăm sóc', deck_id: 2 },
  { front_text: 'turn on', back_text: 'bật lên', deck_id: 2 },
  { front_text: 'turn off', back_text: 'tắt đi', deck_id: 2 },
  { front_text: 'get over', back_text: 'vượt qua', deck_id: 2 },

  // TOEIC Vocabulary (deck_id: 3) - Total 20
  { front_text: 'contract', back_text: 'hợp đồng', deck_id: 3 },
  { front_text: 'assurance', back_text: 'sự cam đoan; bảo đảm', deck_id: 3 },
  { front_text: 'determine', back_text: 'xác định', deck_id: 3 },
  { front_text: 'engage', back_text: 'thu hút; tham gia', deck_id: 3 },
  { front_text: 'establish', back_text: 'thành lập; thiết lập', deck_id: 3 },
  { front_text: 'access', back_text: 'truy cập; lối vào', deck_id: 3 },
  { front_text: 'allocate', back_text: 'phân bổ', deck_id: 3 },
  { front_text: 'compatible', back_text: 'tương thích', deck_id: 3 },
  { front_text: 'delete', back_text: 'xóa bỏ', deck_id: 3 },
  { front_text: 'display', back_text: 'trưng bày; hiển thị', deck_id: 3 },
  { front_text: 'duplicate', back_text: 'sao chép', deck_id: 3 },
  { front_text: 'failure', back_text: 'sự thất bại; hỏng hóc', deck_id: 3 },
  { front_text: 'ignore', back_text: 'phớt lờ', deck_id: 3 },
  { front_text: 'search', back_text: 'tìm kiếm', deck_id: 3 },
  { front_text: 'warning', back_text: 'cảnh báo', deck_id: 3 },
  { front_text: 'affordable', back_text: 'giá cả phải chăng', deck_id: 3 },
  { front_text: 'capacity', back_text: 'sức chứa; năng lực', deck_id: 3 },
  { front_text: 'durable', back_text: 'bền', deck_id: 3 },
  { front_text: 'initiative', back_text: 'sáng kiến', deck_id: 3 },
  { front_text: 'physically', back_text: 'về mặt thể chất; thuộc về vật lý', deck_id: 3 },

  // Business English (deck_id: 4) - Total 20
  { front_text: 'stakeholder', back_text: 'các bên liên quan', deck_id: 4 },
  { front_text: 'revenue', back_text: 'doanh thu', deck_id: 4 },
  { front_text: 'budget', back_text: 'ngân sách', deck_id: 4 },
  { front_text: 'merger', back_text: 'sáp nhập', deck_id: 4 },
  { front_text: 'acquisition', back_text: 'mua lại; thâu tóm', deck_id: 4 },
  { front_text: 'liability', back_text: 'nợ phải trả', deck_id: 4 },
  { front_text: 'asset', back_text: 'tài sản', deck_id: 4 },
  { front_text: 'profit margin', back_text: 'biên lợi nhuận', deck_id: 4 },
  { front_text: 'cash flow', back_text: 'dòng tiền', deck_id: 4 },
  { front_text: 'forecast', back_text: 'dự báo', deck_id: 4 },
  { front_text: 'shareholder', back_text: 'cổ đông', deck_id: 4 },
  { front_text: 'dividend', back_text: 'cổ tức', deck_id: 4 },
  { front_text: 'inflation', back_text: 'lạm phát', deck_id: 4 },
  { front_text: 'market share', back_text: 'thị phần', deck_id: 4 },
  { front_text: 'headquarters', back_text: 'trụ sở chính', deck_id: 4 },
  { front_text: 'subsidiary', back_text: 'công ty con', deck_id: 4 },
  { front_text: 'supply chain', back_text: 'chuỗi cung ứng', deck_id: 4 },
  { front_text: 'negotiation', back_text: 'đàm phán', deck_id: 4 },
  { front_text: 'entrepreneur', back_text: 'doanh nhân', deck_id: 4 },
  { front_text: 'leverage', back_text: 'đòn bẩy; tận dụng', deck_id: 4 },

  // Office Environment & Procedures (deck_id: 5) - Total 20
  { front_text: 'stapler', back_text: 'cái dập ghim', deck_id: 5 },
  { front_text: 'shredder', back_text: 'máy hủy tài liệu', deck_id: 5 },
  { front_text: 'memo', back_text: 'thông báo nội bộ', deck_id: 5 },
  { front_text: 'cubicle', back_text: 'ô làm việc', deck_id: 5 },
  { front_text: 'photocopier', back_text: 'máy photocopy', deck_id: 5 },
  { front_text: 'filing cabinet', back_text: 'tủ đựng hồ sơ', deck_id: 5 },
  { front_text: 'paperclip', back_text: 'kẹp giấy', deck_id: 5 },
  { front_text: 'whiteboard', back_text: 'bảng trắng', deck_id: 5 },
  { front_text: 'marker', back_text: 'bút viết bảng', deck_id: 5 },
  { front_text: 'printer', back_text: 'máy in', deck_id: 5 },
  { front_text: 'scanner', back_text: 'máy quét', deck_id: 5 },
  { front_text: 'desk organizer', back_text: 'khay đựng đồ văn phòng', deck_id: 5 },
  { front_text: 'bulletin board', back_text: 'bảng thông báo', deck_id: 5 },
  { front_text: 'water cooler', back_text: 'bình nước nóng lạnh', deck_id: 5 },
  { front_text: 'conference call', back_text: 'cuộc gọi hội nghị', deck_id: 5 },
  { front_text: 'stationery', back_text: 'văn phòng phẩm', deck_id: 5 },
  { front_text: 'voicemail', back_text: 'thư thoại', deck_id: 5 },
  { front_text: 'spreadsheet', back_text: 'bảng tính', deck_id: 5 },
  { front_text: 'projector screen', back_text: 'màn chiếu', deck_id: 5 },
  { front_text: 'swivel chair', back_text: 'ghế xoay', deck_id: 5 },

  // Meetings & Presentations (deck_id: 6) - Total 20
  { front_text: 'agenda', back_text: 'chương trình nghị sự', deck_id: 6 },
  { front_text: 'minutes', back_text: 'biên bản cuộc họp', deck_id: 6 },
  { front_text: 'projector', back_text: 'máy chiếu', deck_id: 6 },
  { front_text: 'attendee', back_text: 'người tham dự', deck_id: 6 },
  { front_text: 'Q&A session', back_text: 'phiên hỏi đáp', deck_id: 6 },
  { front_text: 'chairperson', back_text: 'chủ tọa', deck_id: 6 },
  { front_text: 'participant', back_text: 'người tham gia', deck_id: 6 },
  { front_text: 'handout', back_text: 'tài liệu phát tay', deck_id: 6 },
  { front_text: 'visual aids', back_text: 'phương tiện trực quan', deck_id: 6 },
  { front_text: 'microphone', back_text: 'micrô', deck_id: 6 },
  { front_text: 'podium', back_text: 'bục phát biểu', deck_id: 6 },
  { front_text: 'brainstorm', back_text: 'động não', deck_id: 6 },
  { front_text: 'feedback', back_text: 'phản hồi', deck_id: 6 },
  { front_text: 'objective', back_text: 'mục tiêu', deck_id: 6 },
  { front_text: 'proposal', back_text: 'đề xuất', deck_id: 6 },
  { front_text: 'follow-up', back_text: 'theo dõi, tiếp nối', deck_id: 6 },
  { front_text: 'summarize', back_text: 'tóm tắt', deck_id: 6 },
  { front_text: 'collaborate', back_text: 'hợp tác', deck_id: 6 },
  { front_text: 'consensus', back_text: 'sự đồng thuận', deck_id: 6 },
  { front_text: 'action items', back_text: 'các mục cần thực hiện', deck_id: 6 },

  // Travel & Accommodation (deck_id: 7) - Total 20
  { front_text: 'itinerary', back_text: 'lịch trình', deck_id: 7 },
  { front_text: 'reservation', back_text: 'sự đặt chỗ trước', deck_id: 7 },
  { front_text: 'boarding pass', back_text: 'thẻ lên máy bay', deck_id: 7 },
  { front_text: 'check-in', back_text: 'làm thủ tục (nhận phòng, lên máy bay)', deck_id: 7 },
  { front_text: 'concierge', back_text: 'nhân viên hướng dẫn (khách sạn)', deck_id: 7 },
  { front_text: 'luggage / baggage', back_text: 'hành lý', deck_id: 7 },
  { front_text: 'carry-on bag', back_text: 'hành lý xách tay', deck_id: 7 },
  { front_text: 'shuttle bus', back_text: 'xe buýt đưa đón', deck_id: 7 },
  { front_text: 'vacancy', back_text: 'phòng trống', deck_id: 7 },
  { front_text: 'amenities', back_text: 'tiện nghi', deck_id: 7 },
  { front_text: 'room service', back_text: 'dịch vụ phòng', deck_id: 7 },
  { front_text: 'front desk / reception', back_text: 'quầy lễ tân', deck_id: 7 },
  { front_text: 'departure lounge', back_text: 'phòng chờ khởi hành', deck_id: 7 },
  { front_text: 'customs', back_text: 'hải quan', deck_id: 7 },
  { front_text: 'immigration', back_text: 'nhập cảnh', deck_id: 7 },
  { front_text: 'connecting flight', back_text: 'chuyến bay chuyển tiếp', deck_id: 7 },
  { front_text: 'layover', back_text: 'thời gian nghỉ giữa các chặng bay', deck_id: 7 },
  { front_text: 'all-inclusive', back_text: 'bao trọn gói', deck_id: 7 },
  { front_text: 'booking confirmation', back_text: 'xác nhận đặt chỗ', deck_id: 7 },
  { front_text: 'currency exchange', back_text: 'đổi tiền tệ', deck_id: 7 },

  // Dining Out & Social Events (deck_id: 8) - Total 20
  { front_text: 'appetizer', back_text: 'món khai vị', deck_id: 8 },
  { front_text: 'main course', back_text: 'món chính', deck_id: 8 },
  { front_text: 'dessert', back_text: 'món tráng miệng', deck_id: 8 },
  { front_text: 'beverage', back_text: 'đồ uống', deck_id: 8 },
  { front_text: 'RSVP (Répondez s\'il vous plaît)', back_text: 'Vui lòng phản hồi (lời mời)', deck_id: 8 },
  { front_text: 'host / hostess', back_text: 'chủ nhà / người tiếp đón', deck_id: 8 },
  { front_text: 'menu', back_text: 'thực đơn', deck_id: 8 },
  { front_text: 'waiter / waitress', back_text: 'bồi bàn nam / nữ', deck_id: 8 },
  { front_text: 'tip / gratuity', back_text: 'tiền boa', deck_id: 8 },
  { front_text: 'bill / check', back_text: 'hóa đơn', deck_id: 8 },
  { front_text: 'cuisine', back_text: 'ẩm thực', deck_id: 8 },
  { front_text: 'side dish', back_text: 'món ăn kèm', deck_id: 8 },
  { front_text: 'cutlery / silverware', back_text: 'dao nĩa', deck_id: 8 },
  { front_text: 'napkin', back_text: 'khăn ăn', deck_id: 8 },
  { front_text: 'buffet', back_text: 'tiệc tự chọn', deck_id: 8 },
  { front_text: 'vegetarian', back_text: 'người ăn chay', deck_id: 8 },
  { front_text: 'sommelier', back_text: 'người phục vụ rượu', deck_id: 8 },
  { front_text: 'set menu', back_text: 'thực đơn cố định', deck_id: 8 },
  { front_text: 'dietary restrictions', back_text: 'hạn chế về chế độ ăn uống', deck_id: 8 },
  { front_text: 'table reservation', back_text: 'đặt bàn', deck_id: 8 },

  // Shopping & Services (deck_id: 9) - Total 20
  { front_text: 'receipt', back_text: 'biên lai, hóa đơn', deck_id: 9 },
  { front_text: 'refund', back_text: 'sự hoàn tiền', deck_id: 9 },
  { front_text: 'discount', back_text: 'sự giảm giá', deck_id: 9 },
  { front_text: 'warranty', back_text: 'phiếu bảo hành', deck_id: 9 },
  { front_text: 'customer service', back_text: 'dịch vụ khách hàng', deck_id: 9 },
  { front_text: 'cashier', back_text: 'nhân viên thu ngân', deck_id: 9 },
  { front_text: 'checkout counter', back_text: 'quầy thanh toán', deck_id: 9 },
  { front_text: 'shopping cart / trolley', back_text: 'xe đẩy hàng', deck_id: 9 },
  { front_text: 'fitting room / changing room', back_text: 'phòng thử đồ', deck_id: 9 },
  { front_text: 'aisle', back_text: 'lối đi giữa các quầy hàng', deck_id: 9 },
  { front_text: 'bargain', back_text: 'mặc cả; món hời', deck_id: 9 },
  { front_text: 'loyalty card', back_text: 'thẻ khách hàng thân thiết', deck_id: 9 },
  { front_text: 'sales tax', back_text: 'thuế bán hàng', deck_id: 9 },
  { front_text: 'out of stock', back_text: 'hết hàng', deck_id: 9 },
  { front_text: 'delivery', back_text: 'giao hàng', deck_id: 9 },
  { front_text: 'online shopping', back_text: 'mua sắm trực tuyến', deck_id: 9 },
  { front_text: 'return policy', back_text: 'chính sách đổi trả', deck_id: 9 },
  { front_text: 'gift voucher', back_text: 'phiếu quà tặng', deck_id: 9 },
  { front_text: 'browse', back_text: 'xem lướt qua', deck_id: 9 },
  { front_text: 'retailer', back_text: 'nhà bán lẻ', deck_id: 9 },

  // Banking & Finance (Advanced) (deck_id: 10) - Total 20
  { front_text: 'overdraft', back_text: 'thấu chi', deck_id: 10 },
  { front_text: 'mortgage', back_text: 'khoản vay thế chấp', deck_id: 10 },
  { front_text: 'interest rate', back_text: 'lãi suất', deck_id: 10 },
  { front_text: 'credit score', back_text: 'điểm tín dụng', deck_id: 10 },
  { front_text: 'wire transfer', back_text: 'chuyển khoản điện tử', deck_id: 10 },
  { front_text: 'debit card', back_text: 'thẻ ghi nợ', deck_id: 10 },
  { front_text: 'credit card', back_text: 'thẻ tín dụng', deck_id: 10 },
  { front_text: 'savings account', back_text: 'tài khoản tiết kiệm', deck_id: 10 },
  { front_text: 'checking account', back_text: 'tài khoản vãng lai', deck_id: 10 }, // US English for 'current account'
  { front_text: 'ATM (Automated Teller Machine)', back_text: 'máy rút tiền tự động', deck_id: 10 },
  { front_text: 'loan', back_text: 'khoản vay', deck_id: 10 },
  { front_text: 'deposit', back_text: 'tiền gửi', deck_id: 10 },
  { front_text: 'withdrawal', back_text: 'rút tiền', deck_id: 10 },
  { front_text: 'balance', back_text: 'số dư', deck_id: 10 },
  { front_text: 'investment', back_text: 'đầu tư', deck_id: 10 },
  { front_text: 'stock market', back_text: 'thị trường chứng khoán', deck_id: 10 },
  { front_text: 'portfolio', back_text: 'danh mục đầu tư', deck_id: 10 },
  { front_text: 'financial statement', back_text: 'báo cáo tài chính', deck_id: 10 },
  { front_text: 'audit', back_text: 'kiểm toán', deck_id: 10 },
  { front_text: 'capital', back_text: 'vốn', deck_id: 10 },

  // Human Resources & Personnel (deck_id: 11) - Total 20
  { front_text: 'résumé / CV', back_text: 'sơ yếu lý lịch', deck_id: 11 },
  { front_text: 'interview', back_text: 'phỏng vấn', deck_id: 11 },
  { front_text: 'probation period', back_text: 'thời gian thử việc', deck_id: 11 },
  { front_text: 'promotion', back_text: 'sự thăng chức', deck_id: 11 },
  { front_text: 'payroll', back_text: 'bảng lương', deck_id: 11 },
  { front_text: 'job description', back_text: 'bản mô tả công việc', deck_id: 11 },
  { front_text: 'cover letter', back_text: 'thư xin việc', deck_id: 11 },
  { front_text: 'benefits package', back_text: 'gói phúc lợi', deck_id: 11 },
  { front_text: 'salary', back_text: 'lương', deck_id: 11 },
  { front_text: 'performance review', back_text: 'đánh giá hiệu suất', deck_id: 11 },
  { front_text: 'recruitment', back_text: 'tuyển dụng', deck_id: 11 },
  { front_text: 'onboarding', back_text: 'quy trình giới thiệu nhân viên mới', deck_id: 11 },
  { front_text: 'resignation', back_text: 'sự từ chức', deck_id: 11 },
  { front_text: 'termination', back_text: 'sự chấm dứt hợp đồng', deck_id: 11 },
  { front_text: 'grievance', back_text: 'khiếu nại (trong công việc)', deck_id: 11 },
  { front_text: 'training', back_text: 'đào tạo', deck_id: 11 },
  { front_text: 'candidate', back_text: 'ứng viên', deck_id: 11 },
  { front_text: 'offer letter', back_text: 'thư mời nhận việc', deck_id: 11 },
  { front_text: 'severance package', back_text: 'gói trợ cấp thôi việc', deck_id: 11 },
  { front_text: 'workforce', back_text: 'lực lượng lao động', deck_id: 11 },

  // Manufacturing & Production (deck_id: 12) - Total 20
  { front_text: 'assembly line', back_text: 'dây chuyền lắp ráp', deck_id: 12 },
  { front_text: 'inventory', back_text: 'hàng tồn kho', deck_id: 12 },
  { front_text: 'quality control', back_text: 'kiểm soát chất lượng', deck_id: 12 },
  { front_text: 'shipment', back_text: 'lô hàng', deck_id: 12 },
  { front_text: 'warehouse', back_text: 'nhà kho', deck_id: 12 },
  { front_text: 'raw materials', back_text: 'nguyên liệu thô', deck_id: 12 },
  { front_text: 'finished goods', back_text: 'thành phẩm', deck_id: 12 },
  { front_text: 'logistics', back_text: 'hậu cần', deck_id: 12 },
  { front_text: 'procurement', back_text: 'thu mua', deck_id: 12 },
  { front_text: 'lead time', back_text: 'thời gian thực hiện', deck_id: 12 },
  { front_text: 'bottleneck', back_text: 'điểm tắc nghẽn (trong sản xuất)', deck_id: 12 },
  { front_text: 'efficiency', back_text: 'hiệu suất', deck_id: 12 },
  { front_text: 'automation', back_text: 'tự động hóa', deck_id: 12 },
  { front_text: 'defect', back_text: 'khuyết tật, lỗi sản phẩm', deck_id: 12 },
  { front_text: 'prototype', back_text: 'nguyên mẫu', deck_id: 12 },
  { front_text: 'mass production', back_text: 'sản xuất hàng loạt', deck_id: 12 },
  { front_text: 'factory', back_text: 'nhà máy', deck_id: 12 },
  { front_text: 'output', back_text: 'sản lượng', deck_id: 12 },
  { front_text: 'workshop', back_text: 'xưởng', deck_id: 12 },
  { front_text: 'machinery', back_text: 'máy móc', deck_id: 12 },

  // Marketing & Advertising (deck_id: 13) - Total 20
  { front_text: 'target audience', back_text: 'khán giả mục tiêu', deck_id: 13 },
  { front_text: 'brand awareness', back_text: 'nhận diện thương hiệu', deck_id: 13 },
  { front_text: 'campaign', back_text: 'chiến dịch', deck_id: 13 },
  { front_text: 'billboard', back_text: 'biển quảng cáo', deck_id: 13 },
  { front_text: 'endorsement', back_text: 'sự quảng cáo (bởi người nổi tiếng)', deck_id: 13 },
  { front_text: 'market research', back_text: 'nghiên cứu thị trường', deck_id: 13 },
  { front_text: 'demographics', back_text: 'nhân khẩu học', deck_id: 13 },
  { front_text: 'public relations (PR)', back_text: 'quan hệ công chúng', deck_id: 13 },
  { front_text: 'press release', back_text: 'thông cáo báo chí', deck_id: 13 },
  { front_text: 'slogan', back_text: 'khẩu hiệu', deck_id: 13 },
  { front_text: 'logo', back_text: 'biểu trưng', deck_id: 13 },
  { front_text: 'social media marketing', back_text: 'tiếp thị qua mạng xã hội', deck_id: 13 },
  { front_text: 'SEO (Search Engine Optimization)', back_text: 'tối ưu hóa công cụ tìm kiếm', deck_id: 13 },
  { front_text: 'commercial', back_text: 'quảng cáo (truyền hình, radio)', deck_id: 13 },
  { front_text: 'product placement', back_text: 'quảng cáo sản phẩm trong phim ảnh, chương trình', deck_id: 13 },
  { front_text: 'focus group', back_text: 'nhóm tập trung (nghiên cứu thị trường)', deck_id: 13 },
  { front_text: 'sales pitch', back_text: 'bài chào hàng', deck_id: 13 },
  { front_text: 'promotion', back_text: 'chương trình khuyến mãi', deck_id: 13 }, // also 'sự thăng chức' but here is marketing context
  { front_text: 'branding', back_text: 'xây dựng thương hiệu', deck_id: 13 },
  { front_text: 'jingle', back_text: 'nhạc hiệu quảng cáo', deck_id: 13 },

  // Technology & IT (deck_id: 14) - Total 20
  { front_text: 'software', back_text: 'phần mềm', deck_id: 14 },
  { front_text: 'hardware', back_text: 'phần cứng', deck_id: 14 },
  { front_text: 'database', back_text: 'cơ sở dữ liệu', deck_id: 14 },
  { front_text: 'firewall', back_text: 'tường lửa', deck_id: 14 },
  { front_text: 'user interface (UI)', back_text: 'giao diện người dùng', deck_id: 14 },
  { front_text: 'operating system (OS)', back_text: 'hệ điều hành', deck_id: 14 },
  { front_text: 'application', back_text: 'ứng dụng', deck_id: 14 },
  { front_text: 'server', back_text: 'máy chủ', deck_id: 14 },
  { front_text: 'network', back_text: 'mạng máy tính', deck_id: 14 },
  { front_text: 'cloud computing', back_text: 'điện toán đám mây', deck_id: 14 },
  { front_text: 'cybersecurity', back_text: 'an ninh mạng', deck_id: 14 },
  { front_text: 'algorithm', back_text: 'thuật toán', deck_id: 14 },
  { front_text: 'programming', back_text: 'lập trình', deck_id: 14 },
  { front_text: 'website', back_text: 'trang web', deck_id: 14 },
  { front_text: 'browser', back_text: 'trình duyệt', deck_id: 14 },
  { front_text: 'download', back_text: 'tải xuống', deck_id: 14 },
  { front_text: 'upload', back_text: 'tải lên', deck_id: 14 },
  { front_text: 'bandwidth', back_text: 'băng thông', deck_id: 14 },
  { front_text: 'bug', back_text: 'lỗi (phần mềm)', deck_id: 14 },
  { front_text: 'user experience (UX)', back_text: 'trải nghiệm người dùng', deck_id: 14 },

  // Real Estate & Housing (deck_id: 15) - Total 20
  { front_text: 'landlord', back_text: 'chủ nhà (cho thuê)', deck_id: 15 },
  { front_text: 'tenant', back_text: 'người thuê nhà', deck_id: 15 },
  { front_text: 'lease agreement', back_text: 'hợp đồng cho thuê', deck_id: 15 },
  { front_text: 'down payment', back_text: 'tiền đặt cọc (mua nhà)', deck_id: 15 },
  { front_text: 'utilities', back_text: 'các tiện ích (điện, nước, gas)', deck_id: 15 },
  { front_text: 'real estate agent', back_text: 'nhân viên môi giới bất động sản', deck_id: 15 },
  { front_text: 'property', back_text: 'bất động sản, tài sản', deck_id: 15 },
  { front_text: 'appraisal', back_text: 'thẩm định giá (bất động sản)', deck_id: 15 },
  { front_text: 'inspection', back_text: 'kiểm tra nhà', deck_id: 15 },
  { front_text: 'closing costs', back_text: 'chi phí chốt hợp đồng (mua bán nhà)', deck_id: 15 },
  { front_text: 'commission', back_text: 'hoa hồng (cho môi giới)', deck_id: 15 },
  { front_text: 'rent', back_text: 'tiền thuê nhà; cho thuê', deck_id: 15 },
  { front_text: 'security deposit', back_text: 'tiền đặt cọc (đảm bảo)', deck_id: 15 },
  { front_text: 'eviction', back_text: 'sự đuổi nhà', deck_id: 15 },
  { front_text: 'homeowner', back_text: 'chủ sở hữu nhà', deck_id: 15 },
  { front_text: 'mortgage broker', back_text: 'người môi giới thế chấp', deck_id: 15 },
  { front_text: 'listing', back_text: 'danh sách (bất động sản bán/cho thuê)', deck_id: 15 },
  { front_text: 'furnishing', back_text: 'đồ đạc trong nhà', deck_id: 15 },
  { front_text: 'renovation', back_text: 'sự cải tạo, sửa chữa nhà', deck_id: 15 },
  { front_text: 'utility bill', back_text: 'hóa đơn tiện ích', deck_id: 15 },

  // Health & Medical (deck_id: 16) - Total 20
  { front_text: 'appointment', back_text: 'cuộc hẹn (với bác sĩ)', deck_id: 16 },
  { front_text: 'prescription', back_text: 'đơn thuốc', deck_id: 16 },
  { front_text: 'symptom', back_text: 'triệu chứng', deck_id: 16 },
  { front_text: 'insurance', back_text: 'bảo hiểm', deck_id: 16 },
  { front_text: 'check-up', back_text: 'kiểm tra sức khỏe tổng quát', deck_id: 16 },
  { front_text: 'diagnosis', back_text: 'chẩn đoán', deck_id: 16 },
  { front_text: 'treatment', back_text: 'điều trị', deck_id: 16 },
  { front_text: 'specialist', back_text: 'bác sĩ chuyên khoa', deck_id: 16 },
  { front_text: 'general practitioner (GP)', back_text: 'bác sĩ đa khoa', deck_id: 16 },
  { front_text: 'emergency room (ER)', back_text: 'phòng cấp cứu', deck_id: 16 },
  { front_text: 'pharmacy', back_text: 'nhà thuốc', deck_id: 16 },
  { front_text: 'vaccine', back_text: 'vắc-xin', deck_id: 16 },
  { front_text: 'side effect', back_text: 'tác dụng phụ', deck_id: 16 },
  { front_text: 'recovery', back_text: 'sự hồi phục', deck_id: 16 },
  { front_text: 'chronic', back_text: 'mãn tính', deck_id: 16 },
  { front_text: 'acute', back_text: 'cấp tính', deck_id: 16 },
  { front_text: 'referral', back_text: 'giấy giới thiệu (đến bác sĩ chuyên khoa)', deck_id: 16 },
  { front_text: 'medical history', back_text: 'tiền sử bệnh án', deck_id: 16 },
  { front_text: 'X-ray', back_text: 'chụp X-quang', deck_id: 16 },
  { front_text: 'blood pressure', back_text: 'huyết áp', deck_id: 16 },

  // Legal Matters (Basic) (deck_id: 17) - Total 20
  { front_text: 'lawsuit', back_text: 'vụ kiện', deck_id: 17 },
  { front_text: 'attorney / lawyer', back_text: 'luật sư', deck_id: 17 },
  { front_text: 'copyright', back_text: 'bản quyền', deck_id: 17 },
  { front_text: 'patent', back_text: 'bằng sáng chế', deck_id: 17 },
  { front_text: 'negotiation', back_text: 'sự đàm phán', deck_id: 17 },
  { front_text: 'agreement', back_text: 'thỏa thuận', deck_id: 17 },
  { front_text: 'plaintiff', back_text: 'nguyên đơn', deck_id: 17 },
  { front_text: 'defendant', back_text: 'bị đơn', deck_id: 17 },
  { front_text: 'litigation', back_text: 'tranh tụng', deck_id: 17 },
  { front_text: 'settlement', back_text: 'sự dàn xếp, hòa giải (pháp lý)', deck_id: 17 },
  { front_text: 'evidence', back_text: 'bằng chứng', deck_id: 17 },
  { front_text: 'witness', back_text: 'nhân chứng', deck_id: 17 },
  { front_text: 'regulation', back_text: 'quy định', deck_id: 17 },
  { front_text: 'compliance', back_text: 'sự tuân thủ (pháp luật, quy định)', deck_id: 17 },
  { front_text: 'intellectual property', back_text: 'sở hữu trí tuệ', deck_id: 17 },
  { front_text: 'liability', back_text: 'trách nhiệm pháp lý', deck_id: 17 },
  { front_text: 'legislation', back_text: 'pháp chế, luật pháp', deck_id: 17 },
  { front_text: 'court', back_text: 'tòa án', deck_id: 17 },
  { front_text: 'dispute', back_text: 'tranh chấp', deck_id: 17 },
  { front_text: 'affidavit', back_text: 'bản khai có tuyên thệ', deck_id: 17 },

  // Weather & Environment (deck_id: 18) - Total 20
  { front_text: 'forecast', back_text: 'dự báo (thời tiết)', deck_id: 18 },
  { front_text: 'humidity', back_text: 'độ ẩm', deck_id: 18 },
  { front_text: 'pollution', back_text: 'sự ô nhiễm', deck_id: 18 },
  { front_text: 'renewable energy', back_text: 'năng lượng tái tạo', deck_id: 18 },
  { front_text: 'climate change', back_text: 'biến đổi khí hậu', deck_id: 18 },
  { front_text: 'temperature', back_text: 'nhiệt độ', deck_id: 18 },
  { front_text: 'precipitation', back_text: 'lượng mưa', deck_id: 18 },
  { front_text: 'drought', back_text: 'hạn hán', deck_id: 18 },
  { front_text: 'flood', back_text: 'lũ lụt', deck_id: 18 },
  { front_text: 'hurricane / typhoon', back_text: 'bão (tùy theo khu vực)', deck_id: 18 },
  { front_text: 'tornado', back_text: 'lốc xoáy', deck_id: 18 },
  { front_text: 'earthquake', back_text: 'động đất', deck_id: 18 },
  { front_text: 'global warming', back_text: 'sự nóng lên toàn cầu', deck_id: 18 },
  { front_text: 'deforestation', back_text: 'nạn phá rừng', deck_id: 18 },
  { front_text: 'conservation', back_text: 'bảo tồn', deck_id: 18 },
  { front_text: 'recycling', back_text: 'tái chế', deck_id: 18 },
  { front_text: 'ecosystem', back_text: 'hệ sinh thái', deck_id: 18 },
  { front_text: 'sustainable', back_text: 'bền vững', deck_id: 18 },
  { front_text: 'carbon footprint', back_text: 'dấu chân carbon', deck_id: 18 },
  { front_text: 'biodegradable', back_text: 'phân hủy sinh học', deck_id: 18 },

  // News & Media (deck_id: 19) - Total 20
  { front_text: 'headline', back_text: 'tiêu đề (bài báo)', deck_id: 19 },
  { front_text: 'journalist', back_text: 'nhà báo', deck_id: 19 },
  { front_text: 'broadcast', back_text: 'chương trình phát sóng', deck_id: 19 },
  { front_text: 'editorial', back_text: 'bài xã luận', deck_id: 19 },
  { front_text: 'source', back_text: 'nguồn tin', deck_id: 19 },
  { front_text: 'article', back_text: 'bài báo', deck_id: 19 },
  { front_text: 'reporter', back_text: 'phóng viên', deck_id: 19 },
  { front_text: 'editor', back_text: 'biên tập viên', deck_id: 19 },
  { front_text: 'photographer', back_text: 'nhiếp ảnh gia', deck_id: 19 },
  { front_text: 'press conference', back_text: 'họp báo', deck_id: 19 },
  { front_text: 'current events', back_text: 'sự kiện thời sự', deck_id: 19 },
  { front_text: 'breaking news', back_text: 'tin nóng, tin giờ chót', deck_id: 19 },
  { front_text: 'coverage', back_text: 'việc đưa tin, phạm vi phủ sóng', deck_id: 19 },
  { front_text: 'censorship', back_text: 'kiểm duyệt', deck_id: 19 },
  { front_text: 'circulation', back_text: 'số lượng phát hành (báo, tạp chí)', deck_id: 19 },
  { front_text: 'bias', back_text: 'sự thiên vị', deck_id: 19 },
  { front_text: 'objective', back_text: 'khách quan', deck_id: 19 }, // adjective here, can also be a noun (goal)
  { front_text: 'scoop', back_text: 'tin sốt dẻo (độc quyền)', deck_id: 19 },
  { front_text: 'correspondent', back_text: 'phóng viên thường trú', deck_id: 19 },
  { front_text: 'publication', back_text: 'ấn phẩm; sự xuất bản', deck_id: 19 },

  // Gerunds & Infinitives (deck_id: 20) - Total 20
  { front_text: 'He enjoys (read) books.', back_text: 'He enjoys reading books. (Danh động từ sau "enjoy")', deck_id: 20 },
  { front_text: 'She decided (study) abroad.', back_text: 'She decided to study abroad. (Động từ nguyên mẫu có "to" sau "decide")', deck_id: 20 },
  { front_text: '(Swim) is good exercise.', back_text: 'Swimming is good exercise. (Danh động từ làm chủ ngữ)', deck_id: 20 },
  { front_text: 'They plan (finish) the project by Friday.', back_text: 'They plan to finish the project by Friday. (Động từ nguyên mẫu có "to" sau "plan")', deck_id: 20 },
  { front_text: 'I look forward to (hear) from you.', back_text: 'I look forward to hearing from you. (Danh động từ sau "look forward to")', deck_id: 20 },
  { front_text: 'I can\'t help (laugh) when I see him.', back_text: 'I can\'t help laughing when I see him. (Danh động từ sau "can\'t help")', deck_id: 20 },
  { front_text: 'They are busy (prepare) for the exam.', back_text: 'They are busy preparing for the exam. (Danh động từ sau "busy")', deck_id: 20 },
  { front_text: 'It\'s important (arrive) on time.', back_text: 'It\'s important to arrive on time. (Động từ nguyên mẫu có "to" sau tính từ "important")', deck_id: 20 },
  { front_text: 'She practices (speak) English every day.', back_text: 'She practices speaking English every day. (Danh động từ sau "practice")', deck_id: 20 },
  { front_text: 'He managed (solve) the problem.', back_text: 'He managed to solve the problem. (Động từ nguyên mẫu có "to" sau "manage")', deck_id: 20 },
  { front_text: '(Read) in dim light is bad for your eyes.', back_text: 'Reading in dim light is bad for your eyes. (Danh động từ làm chủ ngữ)', deck_id: 20 },
  { front_text: 'We agreed (share) the costs.', back_text: 'We agreed to share the costs. (Động từ nguyên mẫu có "to" sau "agree")', deck_id: 20 },
  { front_text: 'I\'m interested in (learn) more about it.', back_text: 'I\'m interested in learning more about it. (Danh động từ sau giới từ "in")', deck_id: 20 },
  { front_text: 'She was advised (see) a doctor.', back_text: 'She was advised to see a doctor. (Động từ nguyên mẫu có "to" sau động từ bị động "was advised")', deck_id: 20 },
  { front_text: 'He quit (smoke) last year.', back_text: 'He quit smoking last year. (Danh động từ sau "quit")', deck_id: 20 },
  { front_text: 'The teacher let us (use) our phones.', back_text: 'The teacher let us use our phones. (Động từ nguyên mẫu không "to" sau "let")', deck_id: 20 },
  { front_text: 'I would rather (stay) home tonight.', back_text: 'I would rather stay home tonight. (Động từ nguyên mẫu không "to" sau "would rather")', deck_id: 20 },
  { front_text: 'She made him (apologize).', back_text: 'She made him apologize. (Động từ nguyên mẫu không "to" sau "make" + tân ngữ)', deck_id: 20 },
  { front_text: 'It is easy (understand) his point.', back_text: 'It is easy to understand his point. (Động từ nguyên mẫu có "to" sau tính từ "easy")', deck_id: 20 },
  { front_text: 'Remember (lock) the door before you leave.', back_text: 'Remember to lock the door before you leave. (Động từ nguyên mẫu có "to" khi "remember" nghĩa là nhớ để làm gì đó)', deck_id: 20 }
];